# render.yaml
services:
  - type: web
    name: drss-laravel-app
    env: docker
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan key:generate
      php artisan migrate --force
      php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://drss-laravel-app.onrender.com
      - key: FILESYSTEM_DISK
        value: public
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: dpg-d1r84eodl3ps73f6asrg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: drss
      - key: DB_USERNAME
        value: sendev
      - key: DB_PASSWORD
        value: qiBMCfYInxTOV03Hm7VMk68FPt1tKN3V
    disk:
      name: persistent-storage
      mountPath: /var/storage
      sizeGB: 1
    ports:
      - port: 10000
        protocol: http
