# render.yaml
services:
  - type: web
    name: drss-laravel-app
    env: php
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan key:generate
      php artisan migrate --force
      php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://drss-laravel-app.onrender.com
      - key: FILESYSTEM_DISK
        value: public
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: YOUR_DB_NAME
      - key: DB_USERNAME
        value: YOUR_DB_USER
      - key: DB_PASSWORD
        value: YOUR_DB_PASSWORD
    disk:
      name: persistent-storage
      mountPath: /var/storage
      sizeGB: 1